import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const roobert = localFont({
  src: [
    {
      path: '../../public/fonts/Roobert-Regular.woff',
      weight: '300',
      style: 'normal',
    }, {
      path: '../../public/fonts/Roobert-SemiBold.woff',
      weight: '600',
      style: 'normal',
    }
  ],
  variable: '--font-roobert-trial'
});
const roobertTrial = localFont({
  src: [
    {
      path: '../../public/fonts/RoobertTRIAL-Regular.woff',
      weight: '300',
      style: 'normal',
    }, {
      path: '../../public/fonts/RoobertTRIAL-SemiBold.woff',
      weight: '600',
      style: 'normal',
    }
  ],
  variable: '--font-roobert'
});

/*const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});*/

export const metadata: Metadata = {
  title: 'Skinstric | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roobertTrial.className}`}>
        <div className='flex flex-col shrink-1 grow-1 basis-auto'>{children}</div>
        <div id='root-portal' />
      </body>
    </html>
  );
}
